'use client';

import Link from 'next/link';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import GaussianVideoWall from '../components/GaussianVideoWall';
import wallData from '../data/gaussian-video-wall.json';

type WallData = {
  generated_at?: string;
  cycle?: number;
  videos?: Array<{
    video_id: string;
    title: string;
    channel?: string;
    published_text?: string;
    url: string;
    embed_url: string;
    thumbnail_url?: string;
    relevance_score?: number;
  }>;
};

const data = wallData as WallData;

export default function GaussianVideoWallPage() {
  const videos = data.videos ?? [];

  return (
    <div>
      <section className="mb-8">
        <div className="flex flex-wrap items-center gap-3 mb-4">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-[var(--text-muted)] hover:text-[var(--foreground)] transition-colors"
          >
            <ArrowLeft size={15} />
            Back
          </Link>
          <span className="badge">Realtime Gaussian Avatar Research Demos</span>
        </div>
        <h1 className="text-3xl font-semibold mb-2">YouTube Video Wall</h1>
        <p className="text-[var(--text-muted)]">
          Click any tile to open a modal player. This wall is generated by the
          <code className="mx-1">gaussian-youtube-video-wall-evolver</code>
          skill.
        </p>
        <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-[var(--text-muted)]">
          <span>
            Updated: {data.generated_at || 'n/a'}
          </span>
          <span>Cycle: {typeof data.cycle === 'number' ? data.cycle : 'n/a'}</span>
          <span>Videos: {videos.length}</span>
        </div>
      </section>

      <section className="mb-10">
        <GaussianVideoWall videos={videos} />
      </section>

      <section className="rounded-xl border border-[var(--border)] bg-[var(--surface-1)] p-4 text-sm text-[var(--text-muted)]">
        <div className="flex items-center gap-2 mb-1">
          <RefreshCw size={15} />
          Refresh command
        </div>
        <code>
          python .claude/skills/gaussian-youtube-video-wall-evolver/scripts/evolve_gaussian_video_wall.py
        </code>
      </section>
    </div>
  );
}
